basePath: /api
definitions:
  model.LapStock:
    properties:
      keluar:
        format: float64
        type: number
      masuk:
        format: float64
        type: number
      productName:
        type: string
      saldo:
        format: float64
        type: number
      sumber:
        type: string
      tanggal:
        type: string
    type: object
  model.Product:
    properties:
      id:
        type: integer
      name:
        type: string
      sku:
        type: string
    type: object
  model.StockIn:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      status:
        type: string
      supplier:
        type: string
      updatedAt:
        type: string
    type: object
  model.StockOut:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      pelanggan:
        type: string
      status:
        type: string
      updatedAt:
        type: string
    type: object
  schema.CreateProductRequest:
    properties:
      name:
        type: string
      sku:
        type: string
    required:
    - name
    - sku
    type: object
  schema.CreateStockInRequest:
    properties:
      items:
        items:
          $ref: '#/definitions/schema.StockInItem'
        type: array
      supplier:
        type: string
    type: object
  schema.CreateStockOutRequest:
    properties:
      items:
        items:
          $ref: '#/definitions/schema.StockOutItem'
        type: array
      pelanggan:
        type: string
    type: object
  schema.StockInItem:
    properties:
      product_id:
        type: integer
      qty:
        type: number
    type: object
  schema.StockOutItem:
    properties:
      product_id:
        type: integer
      qty:
        type: number
    type: object
  schema.UpdateProductRequest:
    properties:
      name:
        type: string
      sku:
        type: string
    type: object
host: localhost:8002
info:
  contact: {}
  description: API untuk sistem inventory
  title: Inventaris API
  version: "1.0"
paths:
  /lap-stok:
    get:
      description: Get stock movement report
      parameters:
      - description: Product Name
        in: query
        name: product_name
        type: string
      - description: Start Date
        in: query
        name: start_date
        type: string
      - description: End Date
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.LapStock'
            type: array
      summary: Get Stock Report
      tags:
      - Report
  /lap-stok/export:
    get:
      description: Export laporan stok ke Excel
      parameters:
      - description: Product Name
        in: query
        name: product_name
        type: string
      - description: Start Date
        in: query
        name: start_date
        type: string
      - description: End Date
        in: query
        name: end_date
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Export Stock Report Excel
      tags:
      - Report
  /products:
    get:
      description: Get all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Product'
            type: array
      summary: Get all products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Create new product
      parameters:
      - description: Create Product
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schema.CreateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create product
      tags:
      - Products
  /products/{id}:
    delete:
      description: Delete product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete product
      tags:
      - Products
    get:
      description: Get single product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get product by ID
      tags:
      - Products
    patch:
      consumes:
      - application/json
      description: Partial update product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      - description: Patch Product
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schema.UpdateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
      summary: Patch product (partial)
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: Full update product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Product
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schema.UpdateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
      summary: Update product (full)
      tags:
      - Products
  /stock-in:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.StockIn'
            type: array
      summary: Get Stock In List
      tags:
      - Stock In
    post:
      consumes:
      - application/json
      parameters:
      - description: Stock In
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schema.CreateStockInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create Stock In (Multi Product)
      tags:
      - Stock In
  /stock-in/{id}:
    get:
      parameters:
      - description: Stock In ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.StockIn'
      summary: Get Stock In Detail
      tags:
      - Stock In
  /stock-in/{id}/cancel:
    post:
      parameters:
      - description: Stock In ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cancel Stock In
      tags:
      - Stock In
  /stock-in/{id}/finish:
    post:
      parameters:
      - description: Stock In ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Finish Stock In
      tags:
      - Stock In
  /stock-out:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.StockOut'
            type: array
      summary: Get Stock Out List
      tags:
      - Stock Out
    post:
      consumes:
      - application/json
      description: Create stock out draft and reserve stock (does not reduce physical
        stock yet)
      parameters:
      - description: Stock Out Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schema.CreateStockOutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Allocate Stock Out (Reserve)
      tags:
      - Stock Out
  /stock-out/{id}:
    get:
      parameters:
      - description: Stock Out ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.StockOut'
            type: array
      summary: Get Stock Out Detail
      tags:
      - Stock Out
  /stock-out/{id}/cancel:
    post:
      description: Cancel stock out and rollback reserved stock
      parameters:
      - description: Stock Out ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cancel Stock Out
      tags:
      - Stock Out
  /stock-out/{id}/finish:
    post:
      description: Finalize stock out and reduce physical stock
      parameters:
      - description: Stock Out ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Finish Stock Out
      tags:
      - Stock Out
swagger: "2.0"
